// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "flash-20181027141056--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://flash-20181027141056--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:eaed4d9c-a295-470f-aeac-5fd8338a7326",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XE5OiTGa2",
    "aws_user_pools_web_client_id": "7ve8cfk17jm625m6vt4ct4422n"
};


export default awsmobile;
